Vagrant.configure("2") do |config|
  #config.proxy.http     = "http://proxy:3128"
  #config.proxy.https    = "http://proxy:3128"
  config.proxy.no_proxy = "localhost,127.0.0.1"
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.name = "dohle-vm"
  end
  config.disksize.size = '20GB'
  config.vagrant.plugins = "vagrant-docker-compose"

  # install docker and docker-compose
  config.vm.provision :docker
  config.vm.provision :docker_compose

  config.vm.provision "shell",
      preserve_order: true,
      inline: <<-SHELL
        apt-get update
        PORTAL_USER="vagrant"
        cp -R /vagrant/Vagrant/deployment/* /home/$PORTAL_USER
        sudo chown vagrant -R .
        cd /home/$PORTAL_USER
        apt-get --assume-yes install dos2unix
        find ./ -type f -exec dos2unix {} \';'
        source full-deployment.sh
        ufw disable
      SHELL
  #config.vm.provision "shell",
  #    preserve_order: true,
  #    run: 'always',
  #    inline: <<-SHELL
  #    SHELL
  #config.vm.network :forwarded_port, guest: 80, host: 80 # nginx
  #config.vm.network :forwarded_port, guest: 443, host: 443 # nginx
  #config.vm.network :forwarded_port, guest: 8080, host: 8081 # wildfly
  #config.vm.network :forwarded_port, guest: 9990, host: 9991 # wildfly management
  #config.vm.network :forwarded_port, guest: 8787, host: 8787 # wildfly debug
  #config.vm.network :forwarded_port, guest: 5432, host: 6432 # postgres
  #config.vm.network :forwarded_port, guest: 8282, host: 8282 # idp
  #config.vm.network :forwarded_port, guest: 90, host: 90 # ihe registry
  #config.vm.network :forwarded_port, guest: 91, host: 91 # ihe repository
  # config.vm.network :forwarded_port, guest: 5601, host: 5601 # kibana
  # config.vm.network :forwarded_port, guest: 9200, host: 9200 # logstash
  #config.vm.network :forwarded_port, guest: 8093, host: 8093 # camunda
  #config.vm.network :forwarded_port, guest: 8094, host: 8094 # camunda dsub listener
  #config.vm.network :forwarded_port, guest: 8095, host: 8095 # fhir
  config.vm.network :forwarded_port, guest: 31337, host: 31337 # tpp of trusted connector
  config.vm.network :forwarded_port, guest: 9000, host: 9000 # portainer
  config.vm.provider "virtualbox" do |v|
      v.memory = 6000
      v.cpus = 3
  end
end