Vagrant.configure("2") do |config|

  config.proxy.http     = "http://proxy:3128"
  config.proxy.https    = "http://proxy:3128"
  config.proxy.no_proxy = "localhost,127.0.0.1"
  config.vm.network "public_network", ip: "192.168.1.20"
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.name = "Draco-vm"
  end
  config.vm.provision "shell",
      preserve_order: true,
      inline: <<-SHELL
        apt-get update
        PORTAL_USER="vagrant"
        cp -R /vagrant/Vagrant/deployment/* /home/$PORTAL_USER
        sudo chown vagrant -R .
        cd /home/$PORTAL_USER
        apt-get --assume-yes install dos2unix
        find ./ -type f -exec dos2unix {} \';'
        source full-deployment.sh
        ufw disable
      SHELL
  #config.vm.provision "shell",
  #    preserve_order: true,
  #    run: 'always',
  #    inline: <<-SHELL
  #    SHELL
     # require plugin https://github.com/leighmcculloch/vagrant-docker-compose
   # vagrant plugin install vagrant-docker-compose
  config.vagrant.plugins = "vagrant-docker-compose"
  config.disksize.size = '50GB'

  # install docker and docker-compose

  #config.vm.network :forwarded_port, guest: 80, host: 80 # nginx
  #config.vm.network :forwarded_port, guest: 443, host: 443 # nginx
  # config.vm.network :forwarded_port, guest: 8080, host: 8081 # wildfly
  # config.vm.network :forwarded_port, guest: 9990, host: 9991 # wildfly management
  # config.vm.network :forwarded_port, guest: 8787, host: 8787 # wildfly debug
  # config.vm.network :forwarded_port, guest: 5432, host: 6432 # postgres
  # config.vm.network :forwarded_port, guest: 8282, host: 8282 # idp
  # config.vm.network :forwarded_port, guest: 90, host: 90 # ihe registry
  # config.vm.network :forwarded_port, guest: 91, host: 91 # ihe repository
  # config.vm.network :forwarded_port, guest: 5601, host: 5601 # kibana
  # config.vm.network :forwarded_port, guest: 9200, host: 9200 # logstash
  config.vm.network :forwarded_port, guest: 9292, host: 9292 # camunda
  config.vm.network :forwarded_port, guest: 1883, host: 1883 # camunda dsub listener
  config.vm.network :forwarded_port, guest: 8081, host: 8081 # 
  config.vm.network :forwarded_port, guest: 8181, host: 8181 # tpm
  config.vm.network :forwarded_port, guest: 9000, host: 9000 # portainer
  config.vm.provider "virtualbox" do |v|
      v.memory = 6000
      v.cpus = 3
      v.gui = true
  end
end
