version: '3.5'
services:
  # Data App (REST consumer, displays web page)
  demo.server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    networks:
      - provider-internal


networks:
  provider-internal:
    name: provider-internal
    driver: bridge

