  
FROM openjdk:11.0.7
RUN apt-get update
RUN apt-get install -y maven
COPY pom.xml /usr/local/service/pom.xml
COPY src /usr/local/service/src
WORKDIR /usr/local/service
RUN mvn package
CMD ["java","-jar","target/docker-1.0-SNAPSHOT-jar-with-dependencies.jar"]
